from __future__ import annotations

from utils.text_cleaning import clean_transcript_text


def render_insurance_report(report_data: dict, language: str = "de") -> str:
    if language == "en":
        sections = [
            "Medical statement for submission to the insurance provider",
            "",
            report_data["recipient"],
            "",
            "Practice data",
            report_data["treating_physician"],
            f"Specialist care: {report_data['specialty']}",
            "Practice address: Not provided",
            "Practice contact: Not provided",
            "",
            "Patient and insurance data",
            f"Patient: {report_data['patient_name']}",
            f"Date of birth: {report_data['patient_dob']}",
            f"Address: {report_data['patient_address']}",
            f"Insurance type: {report_data['insurance_type']}",
            f"Insurance provider: {report_data['insurer']}",
            f"Treatment date: {report_data['treatment_date']}",
            "",
            "Subject",
            report_data["subject"],
            "",
            "Reason for presentation",
            report_data["reason_for_visit"],
            "",
            "History",
            report_data["history"],
            "",
            "Examination findings",
            report_data["findings"],
            "",
            "Diagnostic assessment",
            report_data["assessment"],
            "",
            "Diagnoses",
            _list_items(report_data["diagnoses"]),
            "",
            "Performed medical services",
            _list_items(report_data["services_performed"]),
            "",
            "Treatment / Recommendation",
            report_data["therapy_recommendation"],
            "",
            "Medical justification",
            report_data["medical_justification"],
            "",
            "Billing notes",
            report_data["billing_notes"],
            "",
            "Notice",
            report_data["disclaimer"],
            "",
            report_data["closing"],
            "",
            report_data["treating_physician"],
            "",
            "Place, date",
            "",
            report_data["signature"],
        ]
    else:
        sections = [
            "Ärztliche Stellungnahme zur Vorlage bei der Krankenversicherung",
            "",
            report_data["recipient"],
            "",
            "Praxisdaten",
            report_data["treating_physician"],
            f"Fachärztliche Versorgung: {report_data['specialty']}",
            "Praxisadresse: Nicht angegeben",
            "Praxiskontakt: Nicht angegeben",
            "",
            "Patienten- und Versicherungsdaten",
            f"Patient: {report_data['patient_name']}",
            f"Geburtsdatum: {report_data['patient_dob']}",
            f"Adresse: {report_data['patient_address']}",
            f"Versicherungsart: {report_data['insurance_type']}",
            f"Kostenträger: {report_data['insurer']}",
            f"Behandlungsdatum: {report_data['treatment_date']}",
            "",
            "Betreff",
            report_data["subject"],
            "",
            "Anlass der Vorstellung",
            report_data["reason_for_visit"],
            "",
            "Anamnese",
            report_data["history"],
            "",
            "Untersuchungsbefund",
            report_data["findings"],
            "",
            "Diagnostische Einschätzung / Diagnosen",
            report_data["assessment"],
            "",
            "Diagnosen",
            _list_items(report_data["diagnoses"]),
            "",
            "Durchgeführte ärztliche Leistungen",
            _list_items(report_data["services_performed"]),
            "",
            "Therapie / Empfehlung",
            report_data["therapy_recommendation"],
            "",
            "Medizinische Begründung",
            report_data["medical_justification"],
            "",
            "Abrechnungshinweise",
            report_data["billing_notes"],
            "",
            "Hinweis",
            report_data["disclaimer"],
            "",
            report_data["closing"],
            "",
            report_data["treating_physician"],
            "",
            "Ort, Datum",
            "",
            report_data["signature"],
        ]
    return clean_transcript_text("\n".join(str(part) for part in sections))


def _list_items(items: list[str]) -> str:
    return "\n".join(str(item) for item in items)
